substitutions:
  _MY_BLOG_IMAGE_NAME: my-blog
  _CODE_BLOG_IMAGE_NAME: code-blog
  _STATIC_FILES_IMAGE_NAME: static-files
steps:
- id: my-blog-build-image
  name: gcr.io/cloud-builders/docker
  args: [
    "build",
    "-t", "asia.gcr.io/$PROJECT_ID/$_MY_BLOG_IMAGE_NAME:$BRANCH_NAME",
    "-t", "asia.gcr.io/$PROJECT_ID/$_MY_BLOG_IMAGE_NAME:$SHORT_SHA",
    "docker/my-blog/",
  ]
  waitFor: [
    "-",
  ]
- id: code-blog-build-image
  name: gcr.io/cloud-builders/docker
  args: [
    "build",
    "-t", "asia.gcr.io/$PROJECT_ID/$_CODE_BLOG_IMAGE_NAME:$BRANCH_NAME",
    "-t", "asia.gcr.io/$PROJECT_ID/$_CODE_BLOG_IMAGE_NAME:$SHORT_SHA",
    "docker/code-blog/",
  ]
  waitFor: [
    "-",
  ]
- id: static-files-build-image
  name: gcr.io/cloud-builders/docker
  args: [
    "build",
    "-t", "asia.gcr.io/$PROJECT_ID/$_STATIC_FILES_IMAGE_NAME:$BRANCH_NAME",
    "-t", "asia.gcr.io/$PROJECT_ID/$_STATIC_FILES_IMAGE_NAME:$SHORT_SHA",
    "docker/static-files/",
  ]
  waitFor: [
    "-",
  ]
images:
- asia.gcr.io/$PROJECT_ID/$_MY_BLOG_IMAGE_NAME:$SHORT_SHA
- asia.gcr.io/$PROJECT_ID/$_CODE_BLOG_IMAGE_NAME:$SHORT_SHA
- asia.gcr.io/$PROJECT_ID/$_STATIC_FILES_IMAGE_NAME:$SHORT_SHA
