substitutions:
  _MY_BLOG_IMAGE_NAME: my-blog
  _CODE_BLOG_IMAGE_NAME: code-blog
  _STATIC_FILES_IMAGE_NAME: static-files
steps:
- id: my-blog-build-image
  name: gcr.io/kaniko-project/executor:debug
  args:
  - --context=docker/my-blog/
  - --dockerfile=docker/my-blog/Dockerfile
  - --destination=asia.gcr.io/$PROJECT_ID/$_MY_BLOG_IMAGE_NAME:$SHORT_SHA
  - --cache=true
  - --cache-ttl=6h
  waitFor: ["-"]
- id: code-blog-build-image
  name: gcr.io/kaniko-project/executor:debug
  args:
  - --context=docker/code-blog/
  - --dockerfile=docker/code-blog/Dockerfile
  - --destination=asia.gcr.io/$PROJECT_ID/$_CODE_BLOG_IMAGE_NAME:$SHORT_SHA
  - --cache=true
  - --cache-ttl=6h
  waitFor: ["-"]
- id: static-files-build-image
  name: gcr.io/kaniko-project/executor:debug
  args:
  - --context=docker/static-files/
  - --dockerfile=docker/static-files/Dockerfile
  - --destination=asia.gcr.io/$PROJECT_ID/$_STATIC_FILES_IMAGE_NAME:$SHORT_SHA
  - --cache=true
  - --cache-ttl=6h
  waitFor: ["-"]
