apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-global-config
data:
  nginx.conf: |
    user nginx;
    pid /var/run/nginx.pid;
    worker_processes auto;
    worker_rlimit_nofile 65535;

    events {
      multi_accept on;
      worker_connections 65535;
    }

    http {
      # How long to allow each connection to stay idle; longer values are better
      # for each individual client, particularly for SSL, but means that worker
      # connections are tied up longer. (Default: 65)
      keepalive_timeout 20;

      # Speed up file transfers by using sendfile() to copy directly
      # between descriptors rather than using read()/write().
      sendfile on;

      # Tell Nginx not to send out partial frames; this increases throughput
      # since TCP frames are filled up before being sent out. (adds TCP_CORK)
      tcp_nopush on;

      # Tell Nginx to enable the Nagle buffering algorithm for TCP packets, which
      # collates several smaller packets together into one larger packet, thus saving
      # bandwidth at the cost of a nearly imperceptible increase to latency. (removes TCP_NODELAY)
      tcp_nodelay off;

      # Define the MIME types for files.
      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      access_log /dev/stdout;
      error_log /dev/stderr warn;

      server_tokens off;

      # # security headers
      # add_header X-Frame-Options "SAMEORIGIN" always;
      # add_header X-XSS-Protection "1; mode=block" always;
      # add_header X-Content-Type-Options "nosniff" always;
      # add_header Referrer-Policy "no-referrer-when-downgrade" always;
      # add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'" always;
      # add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

      map $host$request_uri $my_blog_post_id {
        default "";
        vinta.ws/unfuckable/107.html "593";
        vinta.ws/unfuckable/95.html  "635";
        vinta.ws/unfuckable/93.html  "634";
        vinta.ws/unfuckable/92.html  "633";
        vinta.ws/unfuckable/91.html  "632";
        vinta.ws/unfuckable/90.html  "631";
        vinta.ws/unfuckable/89.html  "630";
        vinta.ws/unfuckable/88.html  "629";
        vinta.ws/unfuckable/87.html  "628";
        vinta.ws/unfuckable/86.html  "627";
        vinta.ws/unfuckable/85.html  "626";
        vinta.ws/unfuckable/83.html  "625";
        vinta.ws/unfuckable/81.html  "624";
        vinta.ws/unfuckable/80.html  "623";
        vinta.ws/unfuckable/79.html  "622";
        vinta.ws/unfuckable/74.html  "621";
        vinta.ws/unfuckable/72.html  "620";
        vinta.ws/unfuckable/71.html  "619";
        vinta.ws/unfuckable/70.html  "618";
        vinta.ws/unfuckable/69.html  "617";
        vinta.ws/unfuckable/65.html  "616";
        vinta.ws/unfuckable/64.html  "615";
        vinta.ws/unfuckable/62.html  "614";
        vinta.ws/unfuckable/58.html  "613";
        vinta.ws/unfuckable/36.html  "611";
        vinta.ws/unfuckable/35.html  "610";
        vinta.ws/unfuckable/34.html  "609";
        vinta.ws/unfuckable/38.html  "612";
        vinta.ws/unfuckable/33.html  "608";
        vinta.ws/unfuckable/32.html  "607";
        vinta.ws/unfuckable/31.html  "606";
        vinta.ws/unfuckable/30.html  "605";
        vinta.ws/unfuckable/29.html  "603";
        vinta.ws/unfuckable/28.html  "602";
        vinta.ws/unfuckable/27.html  "601";
        vinta.ws/unfuckable/25.html  "600";
        vinta.ws/unfuckable/24.html  "599";
        vinta.ws/unfuckable/22.html  "598";
        vinta.ws/unfuckable/21.html  "597";
        vinta.ws/unfuckable/18.html  "596";
        vinta.ws/unfuckable/9.html   "605";
      }

      include /etc/nginx/conf.d/*.conf;
    }
  vinta-ws.conf: |
    server {
      listen 80 default;
      server_name vinta.ws;
      root /usr/share/nginx/html;

      location ~ /\.(?!well-known) {
        deny all;
      }

      rewrite ^([^.]*[^/])$ $1/ permanent;

      if ($my_blog_post_id != "") {
        rewrite ^(.*)$ https://vinta.ws/blog/$my_blog_post_id permanent;
      }

      rewrite ^/wordpress/?(.*)$ https://vinta.ws/blog/$1 permanent;
      rewrite ^/unfuckable/(\d+).html$ https://vinta.ws/blog/$1 permanent;
      rewrite ^/unfuckable/$ https://vinta.ws/blog/category/unfuckable/ permanent;

      location / {
        index index.html index.htm;
      }
    }
