apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
      - name: html
        emptyDir: {}
      - name: nginx-global-config
        configMap:
          name: nginx-global-config
      initContainers:
      - name: static-files
        image: asia.gcr.io/vinta-254817/static-files:2d21952
        imagePullPolicy: IfNotPresent
        command: ["cp", "-a", "/var/www/.", "/usr/share/nginx/html/"]
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginx:1.17.4-alpine
        volumeMounts:
        - name: nginx-global-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: nginx-global-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
