# apiVersion: v1
# kind: Service
# metadata:
#   name: nfs-server
# spec:
#   selector:
#     app: nfs-server
#   type: ClusterIP
#   clusterIP: None
#   ports:
#     - name: nfs
#       port: 2049
#     - name: mountd
#       port: 20048
#     - name: rpcbind
#       port: 111
