apiVersion: v1
kind: Service
metadata:
  name: my-blog
spec:
  selector:
    app: my-blog
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: code-blog
spec:
  selector:
    app: code-blog
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
