apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-blog
  template:
    metadata:
      labels:
        app: my-blog
    spec:
      volumes:
      - name: php-fpm-unix-socket
        emptyDir: {}
      - name: wordpress-root
        emptyDir: {}
      - name: nginx-global-config
        configMap:
          name: nginx-global-config
      - name: nginx-wp-includes
        configMap:
          name: nginx-wp-includes
      - name: my-blog-nginx-site
        configMap:
          name: my-blog-nginx-site
      containers:
      - name: wordpress
        image: asia.gcr.io/vinta-254817/my-blog:fa4c1da
        imagePullPolicy: IfNotPresent
        workingDir: /var/www/html/blog # HACK: specify the WordPress installation path
        envFrom:
        - configMapRef:
            name: my-blog-env
        volumeMounts:
        - name: php-fpm-unix-socket
          mountPath: /var/run
        - name: wordpress-root
          mountPath: /var/www/html/blog
      - name: nginx
        image: nginx:1.17.4-alpine
        volumeMounts:
        - name: php-fpm-unix-socket
          mountPath: /var/run
        - name: wordpress-root
          mountPath: /var/www/html/blog
          readOnly: true
        - name: nginx-global-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: nginx-wp-includes
          mountPath: /etc/nginx/includes/
          readOnly: true
        - name: my-blog-nginx-site
          mountPath: /etc/nginx/conf.d/
          readOnly: true
        ports:
        - name: http
          containerPort: 80
        # readinessProbe:
        #   httpGet:
        #     path: /blog/wp-admin/install.php
        #     port: http
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-blog
  template:
    metadata:
      labels:
        app: code-blog
    spec:
      volumes:
      - name: php-fpm-unix-socket
        emptyDir: {}
      - name: wordpress-root
        emptyDir: {}
      - name: code-wp-config
        configMap:
          name: code-wp-config
      - name: nginx-global-config
        configMap:
          name: nginx-global-config
      - name: nginx-wp-includes
        configMap:
          name: nginx-wp-includes
      - name: code-blog-nginx-site
        configMap:
          name: code-blog-nginx-site
      containers:
      - name: wordpress
        image: asia.gcr.io/vinta-254817/code-blog:ca27647
        imagePullPolicy: IfNotPresent
        workingDir: /var/www/html/code # HACK: specify the WordPress installation path
        volumeMounts:
        - name: php-fpm-unix-socket
          mountPath: /var/run
        - name: wordpress-root
          mountPath: /var/www/html/code
        - name: code-wp-config
          mountPath: /var/www/html/code/wp-config.php
          subPath: wp-config.php
      - name: nginx
        image: nginx:1.17.4-alpine
        volumeMounts:
        - name: php-fpm-unix-socket
          mountPath: /var/run
        - name: wordpress-root
          mountPath: /var/www/html/code
          readOnly: true
        - name: nginx-global-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: nginx-wp-includes
          mountPath: /etc/nginx/includes/
          readOnly: true
        - name: code-blog-nginx-site
          mountPath: /etc/nginx/conf.d/
          readOnly: true
        ports:
        - name: http
          containerPort: 80
        # readinessProbe:
        #   httpGet:
        #     path: /code/wp-admin/install.php
        #     port: http
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 256Mi
