# kind: Service
# apiVersion: v1
# metadata:
#   name: mysql
# spec:
#   type: ExternalName
#   externalName: 10.0.0.1

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
